name: CI / Release (No NPM Publish)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout 代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 必须拿到历史 tag

      # 2️⃣ 设置 Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 5️⃣ Semantic Release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_RELEASE_OPTIONS: '{"plugins": ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/changelog", "@semantic-release/git"]}'

