name: CI / Release (No NPM Publish)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout 代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 必须拿到历史 tag

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
