name: Auto Release

on:
  push:
    branches:
      - main

jobs:
      
  release:
    name: Auto Tag + Changelog + Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto Tag
        id: autotag
        uses: anothrNick/github-tag-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: 'v'
          INITIAL_VERSION: 1.0.0
          MAJOR_STRING_TOKEN: BREAKING CHANGE
          MINOR_STRING_TOKEN: feat
          PATCH_STRING_TOKEN: fix | docs | style | refactor | perf | test | chore ｜ ci ｜ build
          RELEASE_BRANCHES: main

      - name: Generate Changelog
        if: steps.autotag.outputs.new_tag != ''
        run: |
          npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.autotag.outputs.new_tag != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.autotag.outputs.new_tag }}
          generateReleaseNotes: true
